export const languageMap: Record<string, string> = {
  af: 'Afrikaans',
  ar: 'Arabic',
  az: 'Azerbaijani',
  bn: 'Bengali',
  bs: 'Bosnian',
  bg: 'Bulgarian',
  ca: 'Catalan',
  cs: 'Czech',
  da: 'Danish',
  'da-dk': 'Danish (Denmark)',
  de: 'German',
  el: 'Greek',
  'el-cy': 'Greek (Cyprus)',
  en: 'English',
  'en-us': 'English (US)',
  'en-gb': 'English (UK)',
  'en-ie': 'English (Ireland)',
  'en-be': 'English (Belgium)',
  'en-pk': 'English (Pakistan)',
  'en-de': 'English (Germany)',
  es: 'Spanish',
  'es-es': 'Spanish (Spain)',
  'es-mx': 'Spanish (Mexico)',
  eu: 'Basque',
  fa: 'Persian',
  fi: 'Finnish',
  fr: 'French',
  'fr-fr': 'French (France)',
  'fr-ca': 'French (Canada)',
  he: 'Hebrew',
  hi: 'Hindi',
  hr: 'Croatian',
  hu: 'Hungarian',
  id: 'Indonesian',
  it: 'Italian',
  ja: 'Japanese',
  ko: 'Korean',
  ku: 'Kurdish',
  lt: 'Lithuanian',
  ms: 'Malay',
  nl: 'Dutch',
  no: 'Norwegian',
  pa: 'Punjabi',
  pl: 'Polish',
  pt: 'Portuguese',
  'pt-br': 'Portuguese (Brazil)',
  'pt-pt': 'Portuguese (Portugal)',
  ro: 'Romanian',
  ru: 'Russian',
  sk: 'Slovak',
  sl: 'Slovenian',
  sq: 'Albanian',
  'sq-al': 'Albanian (Albania)',
  sv: 'Swedish',
  tl: 'Tagalog',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  vi: 'Vietnamese',
  zh: 'Chinese',
  'zh-cn': 'Chinese (Simplified)',
  'zh-tw': 'Chinese (Traditional)',
  'zh-hk': 'Chinese (Hong Kong)'
}
